### ISSUE TITLE
Plugin References must have enabled

### ISSUE THREAD

**Issue by Chelrid** [CelestialSatyr/Clipboard#1]
when the mod is installed, and i start the game this error appears two times.
the game starts, but the mod doesn't work ingame.

![grafik](https://user-images.githubusercontent.com/2716153/182811685-1cc9b809-7ecb-4905-89ff-46d28abb8602.png)

**Comment by CelestialSatyr** [comment]
Added to version 1.0.2, which is available on the launcher now!

**Comment by Chelrid** [comment]
Game start, but after Start Splash Screen this Error appears.

![grafik](https://user-images.githubusercontent.com/2716153/182827497-0ce55193-03c1-45ac-a30e-fc0acb8f5064.png)
