### ISSUE TITLE
Game start, but after Start Splash Screen this Error appears.

### ISSUE THREAD

**Issue by Chelrid** [CelestialSatyr/Clipboard#2]
Game start, but after Start Splash Screen this Error appears.

![grafik](https://user-images.githubusercontent.com/2716153/182827497-0ce55193-03c1-45ac-a30e-fc0acb8f5064.png)

_Originally posted by @Chelrid in https://github.com/CelestialSatyr/Clipboard/issues/1#issuecomment-1205079940_

**Comment by CelestialSatyr** [comment]
New version available (V1.0.4) that should fix the issues!
