### ISSUE TITLE
Clipboard Drop Bug

### ISSUE THREAD

**Issue by chaosfreak93** [CelestialSatyr/Clipboard#4]
**Description of the problem**
> Dropped Clipboards cannot be picked up again

**Desired solution for the problem**
> Make Clipboard collectable

**Comment by chaosfreak93** [comment]
![image](https://user-images.githubusercontent.com/36674649/194777065-604957e6-366b-4008-b3a1-cea11d87381c.png)

**Comment by chaosfreak93** [comment]
Maybe it's related to multiplayer. Haven't tested it in Singleplayer

**Comment by chaosfreak93** [comment]
It could be related to Multiplayer. Haven't tested dropping in Singleplayer.

**Comment by chaosfreak93** [comment]
Any new news/progress?

**Comment by CelestialSatyr** [comment]
Fixed in the current update :)
